# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy site files

on:
  push:
    branches: [ master ]
#     paths-ignore:   # 下列文件的变更不触发部署，可以自行添加
#       - README.md
#       - LICENSE
  pull_request:
    branches: [ master ]

jobs:
  build_and_deploy:

    runs-on: ubuntu-latest
    steps:
    - name: checkout  # 下载代码仓库
      uses: actions/checkout@v2
        
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: "10.x"
          
    - name: build # 打包
      run: |
        cd ./Front
        npm install
        npm run build

    - name: Deploy to Server  # rsync推文件
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
      with:
        flags: '-avzr --delete'
        options: ''
        ssh_options: ''
        src: 'Front/dist'
        dest: '${{secrets.SSH_USERNAME}}@${{secrets.SSH_HOST}}:/usr/share/nginx/html/OCTP'

    - name: Display status from deploy
      run: echo "${{ steps.deploy.outputs.status }}"
  
      
#   with:
#     # Rsync flags
#     flags: -avzr --delete
#     # Local folder to be synced
#     src: ./Front/dist
#     # Remote server and path. i.e user@server.com:/var/www/server.com/
#     dest: : ubuntu@212.64.83.108:/usr/share/nginx/html/OCTP
#         DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}   # 引用配置，SSH私钥
#         flags: -avz --delete
#         SERVER_PORT: '22'  # SSH端口
#         FOLDER: ./Front/dist  # 要推送的文件夹，路径相对于代码仓库的根目录
#         SERVER_IP: ${{ secrets.SSH_HOST }}  # 引用配置，服务器的host名（IP或者域名domain.com）
#         USERNAME: ${{ secrets.SSH_USERNAME }}  # 引用配置，服务器登录名
#         SERVER_DESTINATION: /usr/share/nginx/html   # 部署到目标文件夹

#     - name: Restart server   # 第三步，重启服务
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.SSH_HOST }}  # 下面三个配置与上一步类似
#         username: ${{ secrets.SSH_USERNAME }}
#         key: ${{ secrets.DEPLOY_KEY }}
#         # 重启的脚本，根据自身情况做相应改动，一般要做的是migrate数据库以及重启服务器
#         script: |
#           nginx restart
